version: "3.7"

services:
  account-service:
    build:
      context: .
      dockerfile: ./account-service/app.dockerfile
    depends_on:
      - account_db
    environment:
      DATABASE_URL: postgres://akhil:123456@account_db:5432/akhil?sslmode=disable
    restart: on-failure

  catalog-service:
    build:
      context: .
      dockerfile: ./catalog-service/app.dockerfile
    depends_on:
      - catalog_db
    environment:
      DATABASE_URL: http://catalog_db:9200
    restart: on-failure

  order-service:
    build:
      context: .
      dockerfile: ./order-service/app.dockerfile
    depends_on:
      - order_db
    environment:
      DATABASE_URL: postgres://user:user@order_db:5432/postgres?sslmode=disable
      ACCOUNT_SERVICE_URL: http://account-service:8080
      CATALOG_SERVICE_URL: http://catalog-service:8080
    restart: on-failure

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/app.dockerfile
    ports:
      - 8000:8080
    depends_on:
      - account-service
      - catalog-service
      - order-service
    environment:
      ACCOUNT_SERVICE_URL: http://account-service:8080
      CATALOG_SERVICE_URL: http://catalog-service:8080
      ORDER_SERVICE_URL: http://order-service:8080
    restart: on-failure

  account_db:
    build:
      context: ./account-service
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: akhil
      POSTGRES_USER: akhil
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped

  catalog_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      discovery.type: single-node
    restart: unless-stopped

  order_db:
    build:
      context: ./order-service
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    restart: unless-stopped
